### ISSUE TITLE
Enemies 

### ISSUE THREAD

**Issue by manavvbahl** [UQdeco2800/2021-ext-studio-1#7]
# **Description**
**Task**: Enemies.
**Feature:** Enemy design (Appearance), Enemy Interaction.

The enemy feature will consist of enemy design and appearance following with its own character movement. The enemies will be spawning at intervals within the multiple lanes to attack the main player character ( the player will have to tackle these encounters by switching lanes). Goal of the enemies is to restrict the player before it reaches across hurdle.
 
## **Example**
- While the player reaches the encountering region of enemies. It will have to dodge the enemies before getting trapped into the situation where the enemy has touched the player for which it will lose its health by a certain amount. The movement of enemies would be from right side of the screen and towards the player on the left side, within the lane. (SPRINT 2).
 
# **Dependencies**
- [x] Dependency 1 - Map generation (#10 )
- [x] Dependency 2 - Player interaction (#5)

## **Map generation** 
- Enemy positions will depend upon the map layout for example ( Enemies positioned at multiple lanes ).

 ## **Player Interaction** 
- Every time the player touches the enemies, it will impact in reducing health.
- The enemies could be destroyed by some power-ups collected by the player which lasts for a period of time. (SPRINT 2 Onwards).
 
# **Milestones**

sprint1
- [x] Step 1 (Aug. 20)
- [x] Step 2 (Aug. 23)
- [x] Step 3 (Aug. 26)
- [x] Step 4 (Aug. 30)

Completion Deadline: Aug. 31

eg

    Step 1- Design enemy appearances (Aug.20)
    Step 2- Implementing UI and enemies' design (Aug 23)
    Step 3- Testing (i.e Enemy entity creation and movement). (Aug. 26)
    Step 4- Final check (Aug.30)
    Sprint 1 submission (Aug. 31)

Sprint2

List of steps that need to be completed for this task.
- [x] Step 1 (Sept. 8)
- [x] Step 2 (Sept. 10)
- [x] Step 3 (Sept. 12)
- [x] Step 4 (Sept. 13)

**Completion Deadline:** Sept. 14
 
**Details**
- **Step 1**- Creating and finalizing enemy functions() (Sept. 8)
- **Step 2**- Implementing dynamic feature of enemies (Sept. 10)
- **Step 3**- Testing (i.e Enemy entity creation and movement). (Sept. 12)
- **Step 4**- Final check (Sept. 13)
- **Sprint 2 submission** (Sept. 14)
 
# **Documentation**
## **Enemy Design**
- https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Enemies
## **User Testing**
- https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Enemies-testing

- ...
 
# **Member**
- Manav Bahl (@manavvbahl (Manav Bahl)
- Wanli Yang (@LEONBARBAR (Leon)
- Yiting Liu (@Yiting661)
- Yuming Yin(@Mark-Yuming)

**Comment by uqnjain** [comment]
Overall, the ticket looks good. Try specifying your 'Steps' to highlight significant milestones of your development process. Look forward to reading your documentation (make sure you update those links)!

**Comment by manavvbahl** [comment]
> Overall, the ticket looks good. Try specifying your 'Steps' to highlight significant milestones of your development process. Look forward to reading your documentation (make sure you update those links)!

Hi @uqnjain. The milestone specification has been updated. Could you Please have a look.

**Comment by manavvbahl** [comment]
hi @uqnjain. We have updated the milestones and a slight change in the example of description of the feature ticket for tasks related to sprint 2. could you please have a look and provide some suggestions if any.

**Comment by uqnjain** [comment]
Please update the google docs links with your wiki links.

**Comment by Yiting661** [comment]
> Please update the google docs links with your wiki links.

Hi, @uqnjain , we have finished updating, is there anything else we need to change?
