### ISSUE TITLE
Adding New Buttons to Win Screen

### ISSUE THREAD

**Issue by Abstrusei** [UQdeco2800/2021-ext-studio-1#73]
## Description

Collaborating with Team 6 (creators of the death screen) to integrate their button assets into the Win Screen

### Milestones

- [x] Change current buttons visually
- [x] Get the buttons to function properly e.g. actions, and reactivity 
 
# Members

Sean Marshall (@Abstrusei )

**Comment by adrienerice** [comment]
Hi Sean! So these are the final buttons that we implemented into the death screen, the files have been pushed to main from the previous sprint, but if you need them at all I  have provided them below
![132940354-9a948399-94a3-47eb-a4ce-75713aeed69d](https://user-images.githubusercontent.com/87960378/133887303-d44d171b-288a-4892-8b5d-1927f4a28604.png)
![132940353-f131de41-1542-44ba-a421-6270b67a9747](https://user-images.githubusercontent.com/87960378/133887304-3bee3bc8-80cf-4a77-af45-094625c174e0.png)

!

**Comment by Abstrusei** [comment]
Thanks Adriene! Will get started soon

**Comment by Abstrusei** [comment]
@adrienerice Hey, could you direct me to your feature ticket for the death screen? Struggling to find it

**Comment by Abstrusei** [comment]
Figured it all out.
